# Render Blueprint: deploy this app as a Web Service
# https://render.com/docs/blueprint-spec

services:
  - type: web
    name: highways-data-analysis
    runtime: python

    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
